INSERT INTO tont_zonas (ID,CDZONA,DSNOMBRE) VALUES (1,'Z01','SUDAMERICA');
INSERT INTO tont_zonas (ID,CDZONA,DSNOMBRE) VALUES (2,'Z02','NORTEAMERICA');
INSERT INTO tont_zonas (ID,CDZONA,DSNOMBRE) VALUES (3,'Z03','EUROPA ORIENTAL');